name: CI

# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:    
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        version: [8]
        vm: [hotspot]
        package: [jdk, jre]
        runtype: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1  # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  


      - name: Build - Linux
        if: matrix.os == 'ubuntu-20.04'
        run: bash build_latest.sh ${{ matrix.version }} ${{ matrix.vm }} ${{ matrix.package }} ${{ matrix.runtype }}
        env:
          BUILD_VERSION: ${{ matrix.version }}
          BUILD_OS: ${{ matrix.os }}
          BUILD_VM: ${{ matrix.vm }}
          BUILD_PACKAGE: ${{ matrix.package }}
